[package]
name = "prodlog"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.172"
nix = { version = "0.29.0", features = ["fs", "ioctl", "process", "term"] }
subprocess = "0.2.9"
termion = "4.0.5"
tokio = { version = "1.44.2", features = ["full"] }
